---
- hosts: all
  tasks:
    - name: Gather package facts
      package_facts:
        manager: apt

    - name: Include Apps tasks
      include_tasks: include/apps/{{ item }}.yml
      loop:
        - enpass
        - skype
        - steam
        - spotify
        - vs_code
        - zoom