---
- hosts: all
  tasks:
    - name: Gather package facts
      package_facts:
        manager: apt
        
    - name: Add Spotify Public Key
      raw: curl -sS https://download.spotify.com/debian/pubkey_0D811D58.gpg | apt-key add -      
      when: '"spotify-client" not in ansible_facts.packages'

    - name: Add Spotify as apt source
      raw: echo "deb http://repository.spotify.com stable non-free" | tee /etc/apt/sources.list.d/spotify.list
      when: '"spotify-client" not in ansible_facts.packages'
      
    - name: Apt Update
      raw: apt update -y || true
      when: '"spotify-client" not in ansible_facts.packages'
    
    - name: Install Spotify
      apt:
        name: spotify-client
        state: present
        
    - name: Download Steam Installer
      get_url:
        url: https://steamcdn-a.akamaihd.net/client/installer/steam.deb
        dest: /tmp/steam.deb
        mode: '755'
      when: '"steam-launcher" not in ansible_facts.packages'
      
    - name: Install Steam
      raw: dpkg -i /tmp/steam.deb
      when: '"steam-launcher" not in ansible_facts.packages'
      
    - name: Remove Steam Installer
      file:
        path: /tmp/steam.deb
        state: absent
      when: '"steam-launcher" not in ansible_facts.packages'

