---
- hosts: all
  tasks:
    - name: Gather package facts
      package_facts:
        manager: apt
        
    - name: Include IntelliJ Idea Ultimate tasks
      include_tasks: include/programming/intellij.yml

    - name: Include SQLite Browser tasks
      include_tasks: include/programming/sqlite_browser.yml