---
- hosts: all
  tasks:
    - name: Gather package facts
      package_facts:
        manager: apt
        
      # ENPASS
    - name: Add Enpass repo
      raw: echo "deb https://apt.enpass.io/ stable main" > /etc/apt/sources.list.d/enpass.list
      when: '"enpass" not in ansible_facts.packages'
        
    - name: Import Enpass Key
      raw: wget -O - https://apt.enpass.io/keys/enpass-linux.key | tee /etc/apt/trusted.gpg.d/enpass.asc
      when: '"enpass" not in ansible_facts.packages'
      
    - name: Apt Update (Enpass)
      raw: apt update -y || true
      when: '"enpass" not in ansible_facts.packages'
 
    - name: Install Enpass
      apt:
        name: enpass
        state: present

      # SKYPE
    - name: Download Skype Installer
      get_url: 
        url: https://go.skype.com/skypeforlinux-64.deb
        dest: /tmp/skypeforlinux-64.deb
        mode: '755'
      when: '"skypeforlinux" not in ansible_facts.packages'

    - name: Install Skype
      raw: dpkg -i /tmp/skypeforlinux-64.deb
      when: '"skypeforlinux" not in ansible_facts.packages'
      
    - name: Remove Skype Installer
      file:
        path: /tmp/skypeforlinux-64.deb
        state: absent
      when: '"skypeforlinux" not in ansible_facts.packages'
        
      # STEAM
    - name: Download Steam Installer
      get_url:
        url: https://steamcdn-a.akamaihd.net/client/installer/steam.deb
        dest: /tmp/steam.deb
        mode: '755'
      when: '"steam-launcher" not in ansible_facts.packages'
      
    - name: Install Steam
      raw: dpkg -i /tmp/steam.deb
      when: '"steam-launcher" not in ansible_facts.packages'
      
    - name: Remove Steam Installer
      file:
        path: /tmp/steam.deb
        state: absent
      when: '"steam-launcher" not in ansible_facts.packages'

    - name: Install Steam Deps
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - steam-libs-amd64
    
      # SPOTIFY
    - name: Add Spotify Public Key
      raw: curl -sS https://download.spotify.com/debian/pubkey_0D811D58.gpg | apt-key add -      
      when: '"spotify-client" not in ansible_facts.packages'

    - name: Add Spotify as apt source
      raw: echo "deb http://repository.spotify.com stable non-free" | tee /etc/apt/sources.list.d/spotify.list
      when: '"spotify-client" not in ansible_facts.packages'
      
    - name: Apt Update (Spotify)
      raw: apt update -y || true
      when: '"spotify-client" not in ansible_facts.packages'
    
    - name: Install Spotify
      apt:
        name: spotify-client
        state: present
    
