---
- import_playbook: apps/enpass.yml

- hosts: all
  tasks:
    - name: Gather package facts
      package_facts:
        manager: apt

    - name: Include Enpass tasks
      include_tasks: include/enpass.yml
      
    - name: Include Skype tasks
      include_tasks: include/skype.yml
        
    - name: Include Steam tasks
      include_tasks: include/steam.yml
    
    - name: Include Spotify tasks
      include_tasks: include/spotify.yml
        
      # VS Code
    - name: Install Visual Studio Code
      snap:
        name: code
        classic: yes
    
