---
- hosts: all
  tasks:
    - name: Gather package facts
      package_facts:
        manager: apt

    - name: Include Programming tasks
      include_tasks: include/programming/{{ item }}.yml
      loop:
        - intellij
        - sqlite_browser
