---
- hosts: all
  tasks:
    - name: Install VIM
      apt:
        name: vim
        state: present
    
    - name: Install Git
      apt:
        name: git
        state: present
        
    - name: Install dos2unix
      apt:
        name: dos2unix
        state: present
        
    - name: Install software-properties-common
      apt:
        name: software-properties-common
        state: present
        
    - name: Install Python 3
      apt: 
        name: python3
        state: present
        
    - name: Add Spotify Public Key
      raw: curl -sS https://download.spotify.com/debian/pubkey_0D811D58.gpg | apt-key add -      

    - name: Add Spotify as apt source
      raw: echo "deb http://repository.spotify.com stable non-free" | tee /etc/apt/sources.list.d/spotify.list
      
    - name: Apt Update
      raw: apt update -y || true
    
    - name: Install Spotify
      apt:
        name: spotify-client
        state: present

