# This file is meant to be included via an 'include_tasks' task in a 'parent' playbook.
# Assumes apt's 'package_facts' task has been run earlier
- hosts: all
  tasks:
  - name: Gather package facts
    package_facts:
      manager: apt

  - name: Add Enpass repo
    raw: echo "deb https://apt.enpass.io/ stable main" > /etc/apt/sources.list.d/enpass.list
    when: '"enpass" not in ansible_facts.packages'
      
  - name: Import Enpass Key
    raw: wget -O - https://apt.enpass.io/keys/enpass-linux.key | tee /etc/apt/trusted.gpg.d/enpass.asc
    when: '"enpass" not in ansible_facts.packages'
    
  - name: Apt Update (Enpass)
    raw: apt update -y || true
    when: '"enpass" not in ansible_facts.packages'

  - name: Install Enpass
    apt:
      name: enpass
      state: present
